// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupExportPackage() {
  return window['go']['main']['App']['BackupExportPackage']();
}

export function BackupGetManifestTemplate() {
  return window['go']['main']['App']['BackupGetManifestTemplate']();
}

export function BackupGetScopeDefinition() {
  return window['go']['main']['App']['BackupGetScopeDefinition']();
}

export function BackupImportPackage(arg1) {
  return window['go']['main']['App']['BackupImportPackage'](arg1);
}

export function BackupInitializeSystem() {
  return window['go']['main']['App']['BackupInitializeSystem']();
}

export function BookmarkList() {
  return window['go']['main']['App']['BookmarkList']();
}

export function BookmarkReset() {
  return window['go']['main']['App']['BookmarkReset']();
}

export function BookmarkSave(arg1) {
  return window['go']['main']['App']['BookmarkSave'](arg1);
}

export function BrowserClearCookies(arg1) {
  return window['go']['main']['App']['BrowserClearCookies'](arg1);
}

export function BrowserCoreDelete(arg1) {
  return window['go']['main']['App']['BrowserCoreDelete'](arg1);
}

export function BrowserCoreDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserCoreDownload'](arg1, arg2, arg3);
}

export function BrowserCoreExtendedInfo() {
  return window['go']['main']['App']['BrowserCoreExtendedInfo']();
}

export function BrowserCoreList() {
  return window['go']['main']['App']['BrowserCoreList']();
}

export function BrowserCoreSave(arg1) {
  return window['go']['main']['App']['BrowserCoreSave'](arg1);
}

export function BrowserCoreScan() {
  return window['go']['main']['App']['BrowserCoreScan']();
}

export function BrowserCoreSetDefault(arg1) {
  return window['go']['main']['App']['BrowserCoreSetDefault'](arg1);
}

export function BrowserCoreValidate(arg1) {
  return window['go']['main']['App']['BrowserCoreValidate'](arg1);
}

export function BrowserExportCookies(arg1) {
  return window['go']['main']['App']['BrowserExportCookies'](arg1);
}

export function BrowserGetAllTags() {
  return window['go']['main']['App']['BrowserGetAllTags']();
}

export function BrowserGetCookies(arg1) {
  return window['go']['main']['App']['BrowserGetCookies'](arg1);
}

export function BrowserInstanceGetTabs(arg1) {
  return window['go']['main']['App']['BrowserInstanceGetTabs'](arg1);
}

export function BrowserInstanceOpenUrl(arg1, arg2) {
  return window['go']['main']['App']['BrowserInstanceOpenUrl'](arg1, arg2);
}

export function BrowserInstanceRestart(arg1) {
  return window['go']['main']['App']['BrowserInstanceRestart'](arg1);
}

export function BrowserInstanceStart(arg1) {
  return window['go']['main']['App']['BrowserInstanceStart'](arg1);
}

export function BrowserInstanceStartByCode(arg1) {
  return window['go']['main']['App']['BrowserInstanceStartByCode'](arg1);
}

export function BrowserInstanceStartWithParams(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserInstanceStartWithParams'](arg1, arg2, arg3, arg4);
}

export function BrowserInstanceStatus(arg1) {
  return window['go']['main']['App']['BrowserInstanceStatus'](arg1);
}

export function BrowserInstanceStop(arg1) {
  return window['go']['main']['App']['BrowserInstanceStop'](arg1);
}

export function BrowserProfileBatchRemoveTags(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileBatchRemoveTags'](arg1, arg2);
}

export function BrowserProfileBatchSetTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserProfileBatchSetTags'](arg1, arg2, arg3);
}

export function BrowserProfileCopy(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileCopy'](arg1, arg2);
}

export function BrowserProfileCreate(arg1) {
  return window['go']['main']['App']['BrowserProfileCreate'](arg1);
}

export function BrowserProfileDelete(arg1) {
  return window['go']['main']['App']['BrowserProfileDelete'](arg1);
}

export function BrowserProfileGetCode(arg1) {
  return window['go']['main']['App']['BrowserProfileGetCode'](arg1);
}

export function BrowserProfileList() {
  return window['go']['main']['App']['BrowserProfileList']();
}

export function BrowserProfileListByTag(arg1) {
  return window['go']['main']['App']['BrowserProfileListByTag'](arg1);
}

export function BrowserProfileRegenerateCode(arg1) {
  return window['go']['main']['App']['BrowserProfileRegenerateCode'](arg1);
}

export function BrowserProfileSetCode(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetCode'](arg1, arg2);
}

export function BrowserProfileSetKeywords(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetKeywords'](arg1, arg2);
}

export function BrowserProfileUpdate(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileUpdate'](arg1, arg2);
}

export function BrowserProxyBatchCheckIPHealth(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchCheckIPHealth'](arg1, arg2);
}

export function BrowserProxyBatchTestSpeed(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchTestSpeed'](arg1, arg2);
}

export function BrowserProxyCheckIPHealth(arg1) {
  return window['go']['main']['App']['BrowserProxyCheckIPHealth'](arg1);
}

export function BrowserProxyFetchClashByURL(arg1) {
  return window['go']['main']['App']['BrowserProxyFetchClashByURL'](arg1);
}

export function BrowserProxyList() {
  return window['go']['main']['App']['BrowserProxyList']();
}

export function BrowserProxyListByGroup(arg1) {
  return window['go']['main']['App']['BrowserProxyListByGroup'](arg1);
}

export function BrowserProxyListGroups() {
  return window['go']['main']['App']['BrowserProxyListGroups']();
}

export function BrowserProxyTestSpeed(arg1) {
  return window['go']['main']['App']['BrowserProxyTestSpeed'](arg1);
}

export function BrowserRenameTag(arg1, arg2) {
  return window['go']['main']['App']['BrowserRenameTag'](arg1, arg2);
}

export function BrowserSnapshotCreate(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotCreate'](arg1, arg2);
}

export function BrowserSnapshotDelete(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotDelete'](arg1, arg2);
}

export function BrowserSnapshotList(arg1) {
  return window['go']['main']['App']['BrowserSnapshotList'](arg1);
}

export function BrowserSnapshotRestore(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotRestore'](arg1, arg2);
}

export function ClearAppLogs() {
  return window['go']['main']['App']['ClearAppLogs']();
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function FetchRemoteAuthorProfile(arg1, arg2) {
  return window['go']['main']['App']['FetchRemoteAuthorProfile'](arg1, arg2);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetBrowserSettings() {
  return window['go']['main']['App']['GetBrowserSettings']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetInterceptor() {
  return window['go']['main']['App']['GetInterceptor']();
}

export function GetLaunchServerInfo() {
  return window['go']['main']['App']['GetLaunchServerInfo']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetRunningInstances() {
  return window['go']['main']['App']['GetRunningInstances']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function MoveInstancesToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveInstancesToGroup'](arg1, arg2);
}

export function OpenCorePath(arg1) {
  return window['go']['main']['App']['OpenCorePath'](arg1);
}

export function OpenUserDataDir(arg1) {
  return window['go']['main']['App']['OpenUserDataDir'](arg1);
}

export function QuitAppOnly() {
  return window['go']['main']['App']['QuitAppOnly']();
}

export function RPAFlowDelete(arg1) {
  return window['go']['main']['App']['RPAFlowDelete'](arg1);
}

export function RPAFlowEncodeXML(arg1) {
  return window['go']['main']['App']['RPAFlowEncodeXML'](arg1);
}

export function RPAFlowExportXML(arg1) {
  return window['go']['main']['App']['RPAFlowExportXML'](arg1);
}

export function RPAFlowGroupCreate(arg1) {
  return window['go']['main']['App']['RPAFlowGroupCreate'](arg1);
}

export function RPAFlowGroupList() {
  return window['go']['main']['App']['RPAFlowGroupList']();
}

export function RPAFlowImportByShareCode(arg1) {
  return window['go']['main']['App']['RPAFlowImportByShareCode'](arg1);
}

export function RPAFlowImportXML(arg1) {
  return window['go']['main']['App']['RPAFlowImportXML'](arg1);
}

export function RPAFlowList(arg1, arg2) {
  return window['go']['main']['App']['RPAFlowList'](arg1, arg2);
}

export function RPAFlowParseXML(arg1) {
  return window['go']['main']['App']['RPAFlowParseXML'](arg1);
}

export function RPAFlowSave(arg1) {
  return window['go']['main']['App']['RPAFlowSave'](arg1);
}

export function RPAFlowShare(arg1) {
  return window['go']['main']['App']['RPAFlowShare'](arg1);
}

export function RPARunList() {
  return window['go']['main']['App']['RPARunList']();
}

export function RPARunTargetList(arg1) {
  return window['go']['main']['App']['RPARunTargetList'](arg1);
}

export function RPATaskDelete(arg1) {
  return window['go']['main']['App']['RPATaskDelete'](arg1);
}

export function RPATaskExecute(arg1) {
  return window['go']['main']['App']['RPATaskExecute'](arg1);
}

export function RPATaskGet(arg1) {
  return window['go']['main']['App']['RPATaskGet'](arg1);
}

export function RPATaskList() {
  return window['go']['main']['App']['RPATaskList']();
}

export function RPATaskSave(arg1, arg2) {
  return window['go']['main']['App']['RPATaskSave'](arg1, arg2);
}

export function RPATemplateCreateFlow(arg1) {
  return window['go']['main']['App']['RPATemplateCreateFlow'](arg1);
}

export function RPATemplateDelete(arg1) {
  return window['go']['main']['App']['RPATemplateDelete'](arg1);
}

export function RPATemplateList() {
  return window['go']['main']['App']['RPATemplateList']();
}

export function RPATemplateSave(arg1) {
  return window['go']['main']['App']['RPATemplateSave'](arg1);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SaveBrowserProxies(arg1) {
  return window['go']['main']['App']['SaveBrowserProxies'](arg1);
}

export function SaveBrowserSettings(arg1) {
  return window['go']['main']['App']['SaveBrowserSettings'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StartInstanceWithParams(arg1, arg2) {
  return window['go']['main']['App']['StartInstanceWithParams'](arg1, arg2);
}

export function TestProxyConnectivity(arg1, arg2) {
  return window['go']['main']['App']['TestProxyConnectivity'](arg1, arg2);
}

export function TestProxyRealConnectivity(arg1) {
  return window['go']['main']['App']['TestProxyRealConnectivity'](arg1);
}

export function TriggerGC() {
  return window['go']['main']['App']['TriggerGC']();
}

export function UpdateGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2);
}

export function ValidateProxyConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateProxyConfig'](arg1, arg2);
}
