// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {config} from '../models';
import {browser} from '../models';
import {backend} from '../models';
import {logger} from '../models';
import {rpa} from '../models';
import {launchcode} from '../models';

export function BackupExportPackage():Promise<Record<string, any>>;

export function BackupGetManifestTemplate():Promise<backup.Manifest>;

export function BackupGetScopeDefinition():Promise<backup.Scope>;

export function BackupImportPackage(arg1:boolean):Promise<Record<string, any>>;

export function BackupInitializeSystem():Promise<Record<string, any>>;

export function BookmarkList():Promise<Array<config.BrowserBookmark>>;

export function BookmarkReset():Promise<void>;

export function BookmarkSave(arg1:Array<config.BrowserBookmark>):Promise<void>;

export function BrowserClearCookies(arg1:string):Promise<void>;

export function BrowserCoreDelete(arg1:string):Promise<void>;

export function BrowserCoreDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowserCoreExtendedInfo():Promise<Array<browser.CoreExtendedInfo>>;

export function BrowserCoreList():Promise<Array<config.BrowserCore>>;

export function BrowserCoreSave(arg1:browser.CoreInput):Promise<void>;

export function BrowserCoreScan():Promise<Array<config.BrowserCore>>;

export function BrowserCoreSetDefault(arg1:string):Promise<void>;

export function BrowserCoreValidate(arg1:string):Promise<browser.CoreValidateResult>;

export function BrowserExportCookies(arg1:string):Promise<string>;

export function BrowserGetAllTags():Promise<Array<string>>;

export function BrowserGetCookies(arg1:string):Promise<Array<backend.CookieInfo>>;

export function BrowserInstanceGetTabs(arg1:string):Promise<Array<browser.Tab>>;

export function BrowserInstanceOpenUrl(arg1:string,arg2:string):Promise<boolean>;

export function BrowserInstanceRestart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartByCode(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartWithParams(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<browser.Profile>;

export function BrowserInstanceStatus(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStop(arg1:string):Promise<browser.Profile>;

export function BrowserProfileBatchRemoveTags(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function BrowserProfileBatchSetTags(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<void>;

export function BrowserProfileCopy(arg1:string,arg2:string):Promise<browser.Profile>;

export function BrowserProfileCreate(arg1:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProfileDelete(arg1:string):Promise<void>;

export function BrowserProfileGetCode(arg1:string):Promise<string>;

export function BrowserProfileList():Promise<Array<browser.Profile>>;

export function BrowserProfileListByTag(arg1:string):Promise<Array<browser.Profile>>;

export function BrowserProfileRegenerateCode(arg1:string):Promise<string>;

export function BrowserProfileSetCode(arg1:string,arg2:string):Promise<string>;

export function BrowserProfileSetKeywords(arg1:string,arg2:Array<string>):Promise<browser.Profile>;

export function BrowserProfileUpdate(arg1:string,arg2:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProxyBatchCheckIPHealth(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyIPHealthResult>>;

export function BrowserProxyBatchTestSpeed(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyTestResult>>;

export function BrowserProxyCheckIPHealth(arg1:string):Promise<backend.ProxyIPHealthResult>;

export function BrowserProxyFetchClashByURL(arg1:string):Promise<Record<string, any>>;

export function BrowserProxyList():Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListByGroup(arg1:string):Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListGroups():Promise<Array<string>>;

export function BrowserProxyTestSpeed(arg1:string):Promise<backend.ProxyTestResult>;

export function BrowserRenameTag(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotCreate(arg1:string,arg2:string):Promise<backend.SnapshotInfo>;

export function BrowserSnapshotDelete(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotList(arg1:string):Promise<Array<backend.SnapshotInfo>>;

export function BrowserSnapshotRestore(arg1:string,arg2:string):Promise<void>;

export function ClearAppLogs():Promise<void>;

export function CreateGroup(arg1:browser.GroupInput):Promise<browser.Group>;

export function DeleteGroup(arg1:string):Promise<void>;

export function FetchRemoteAuthorProfile(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ForceQuit():Promise<void>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetAppLogs():Promise<Array<logger.MemoryLogEntry>>;

export function GetBrowserSettings():Promise<browser.Settings>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetInterceptor():Promise<logger.MethodInterceptor>;

export function GetLaunchServerInfo():Promise<Record<string, any>>;

export function GetLogLevel():Promise<string>;

export function GetMemoryStats():Promise<Record<string, any>>;

export function GetRunningInstances():Promise<Array<browser.Profile>>;

export function ListGroups():Promise<Array<browser.GroupWithCount>>;

export function MoveInstancesToGroup(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenCorePath(arg1:string):Promise<void>;

export function OpenUserDataDir(arg1:string):Promise<void>;

export function QuitAppOnly():Promise<void>;

export function RPAFlowDelete(arg1:string):Promise<void>;

export function RPAFlowEncodeXML(arg1:rpa.Flow):Promise<string>;

export function RPAFlowExportXML(arg1:string):Promise<string>;

export function RPAFlowGroupCreate(arg1:rpa.FlowGroupInput):Promise<rpa.FlowGroup>;

export function RPAFlowGroupList():Promise<Array<rpa.FlowGroup>>;

export function RPAFlowImportByShareCode(arg1:string):Promise<rpa.Flow>;

export function RPAFlowImportXML(arg1:rpa.FlowXMLImportInput):Promise<rpa.Flow>;

export function RPAFlowList(arg1:string,arg2:string):Promise<Array<rpa.Flow>>;

export function RPAFlowNodeCatalog():Promise<rpa.FlowNodeCatalogPayload>;

export function RPAFlowParseXML(arg1:rpa.FlowXMLImportInput):Promise<rpa.Flow>;

export function RPAFlowSave(arg1:rpa.Flow):Promise<rpa.Flow>;

export function RPAFlowShare(arg1:string):Promise<string>;

export function RPARunList():Promise<Array<rpa.Run>>;

export function RPARunStepList(arg1:string):Promise<Array<rpa.RunStep>>;

export function RPARunTargetList(arg1:string):Promise<Array<rpa.RunTarget>>;

export function RPATaskDelete(arg1:string):Promise<void>;

export function RPATaskExecute(arg1:string):Promise<rpa.Run>;

export function RPATaskGet(arg1:string):Promise<rpa.TaskDetail>;

export function RPATaskList():Promise<Array<rpa.Task>>;

export function RPATaskSave(arg1:rpa.Task,arg2:Array<rpa.TaskTarget>):Promise<rpa.Task>;

export function RPATemplateCreateFlow(arg1:string):Promise<rpa.Flow>;

export function RPATemplateDelete(arg1:string):Promise<void>;

export function RPATemplateList():Promise<Array<rpa.Template>>;

export function RPATemplateSave(arg1:rpa.Template):Promise<rpa.Template>;

export function ReloadConfig():Promise<void>;

export function SaveBrowserProxies(arg1:Array<config.BrowserProxy>):Promise<void>;

export function SaveBrowserSettings(arg1:browser.Settings):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function StartInstance(arg1:string):Promise<browser.Profile>;

export function StartInstanceWithParams(arg1:string,arg2:launchcode.LaunchRequestParams):Promise<browser.Profile>;

export function TestProxyConnectivity(arg1:string,arg2:string):Promise<backend.ProxyTestResult>;

export function TestProxyRealConnectivity(arg1:string):Promise<backend.ProxyTestResult>;

export function TriggerGC():Promise<void>;

export function UpdateGroup(arg1:string,arg2:browser.GroupInput):Promise<browser.Group>;

export function ValidateProxyConfig(arg1:string,arg2:string):Promise<backend.ProxyValidationResult>;
